# This workflow is named "Java CI with Maven"
name: Java CI with Maven

# This workflow will run on any push to the "main" branch
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  # The name of the job is "build"
  build:
    # It will run on the latest version of Ubuntu
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checks out your repository code, so the workflow can access it
    - uses: actions/checkout@v4

    # Step 2: Sets up JDK 17, which our project needs
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven

    # Step 3: Builds the project and runs ALL tests with Maven
    # 'mvn -B verify' is a standard command that compiles, tests, and packages the code.
    # It will automatically run our JUnit, Cucumber, and REST Assured tests.
    - name: Build and Test with Maven
      run: mvn -B verify --file pom.xml
